### ISSUE TITLE
XSLT fails with undeclared parameter failure

### ISSUE THREAD

**Issue by drmacro** [dita4publishers/org.dita4publishers.html2#6]
```
     [xslt] /Applications/oxygen/frameworks/dita/DITA-OT/xsl/common/dita-utilities.xsl:8:80: Warning! Stylesheet module plugin:org.dita.base:xsl/common/dita-utilities.xsl is included or imported more than once. This is permitted, but may lead to errors or unexpected behavior
     [xslt] /Applications/oxygen/frameworks/dita/DITA-OT/plugins/net.sourceforge.dita4publishers.html2/xsl/map2html2DynamicToc.xsl:223:69: Fatal Error! Parameter parentId is not declared in the called template
     [xslt] /Applications/oxygen/frameworks/dita/DITA-OT/plugins/net.sourceforge.dita4publishers.html2/xsl/map2html2DynamicToc.xsl:235:69: Fatal Error! Parameter parentId is not declared in the called template
     [xslt] /Applications/oxygen/frameworks/dita/DITA-OT/plugins/net.sourceforge.dita4publishers.html2/xsl/map2html2DynamicToc.xsl:249:69: Fatal Error! Parameter parentId is not declared in the called template
     [xslt] Failed to process null
```

**Comment by drmacro** [comment]
Current code doesn't have this issue.

**Comment by gvinodkumar515** [comment]
Current code having this issue.

F [DITA-OT] Transformation failed.

F [DITA-OT] Cannot find a matching 4-argument function named {http://dita4publishers.org/functions/htmlutil}getTopicResultUrl2()

F [DITA-OT] Cannot find a matching 4-argument function named {http://dita4publishers.org/functions/htmlutil}getTopicResultUrl2()

F [DITA-OT] Cannot find a matching 4-argument function named {http://dita4publishers.org/functions/htmlutil}getTopicResultUrl2()

**Comment by paperdigits** [comment]
What version of the open toolkit are you using? What version of the html2 plugin?

**Comment by gvinodkumar515** [comment]
DITA OT 1.8.5 and html2 plugin from https://github.com/dita4publishers/org.dita4publishers.html2

**Comment by paperdigits** [comment]
Have you tried the latest applicable plugins from https://github.com/dita4publishers/dita4publishers/releases ?

**Comment by gvinodkumar515** [comment]
Yes I am using those plugins only in DITA OT 1.8.5

**Comment by paperdigits** [comment]
Can you use the HTML5 plugin? Its a bug in the plugin and it isn't currently being maintained.

**Comment by gvinodkumar515** [comment]
I can't use the HTML5 Because for my requirements HTML2 plugin useful.

**Comment by paperdigits** [comment]
I believe the included HTML2/XHTML plugin from Open Toolkit still works. You could try that. 

Otherwise you'll need to fix the errors for this plugin yourself for the time being. Patches are welcome :)
